### PR TITLE
Added Michael

### PR DESCRIPTION
**Pull request by Michaelfonzolo**

### CODE REVIEW

**Comment by Drag0n0x** [comment]
you suck

**Comment by roflwaffl** [comment]
you suck

**Comment by Michaelfonzolo** [comment]
fuck off

**Comment by roflwaffl** [comment]
wow flame more noob

**Comment by Drag0n0x** [comment]
mad cuz bad

**Comment by Michaelfonzolo** [comment]
What the fuck did you just fucking say about me, you little shit? Ill have you know I graduated top of my class in the Navy Seals, and Ive been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and Im the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. Youre fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and thats just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little clever comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldnt, you didnt, and now youre paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. Youre fucking dead, kiddo.

**Comment by Drag0n0x** [comment]
I sexually Identify as an Attack Helicopter. Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners. People say to me that a person being a helicopter is Impossible and I'm fucking retarded but I don't care, I'm beautiful. I'm having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body. From now on I want you guys to call me "Apache" and respect my right to kill from above and kill needlessly. If you can't accept me you're a heliphobe and need to check your vehicle privilege. Thank you for being so understanding.

**Comment by roflwaffl** [comment]
What the heck did you just flipping say about me, you big meanie? I'll have you know I graduated top of my class in the Tiny Tots Program, and I've been involved in numerous secret raids on the girl's bathroom, and I have over 300 confirmed noogies. I am trained in Nerf warfare and I have the most gold stars in the entire kindergarten class. You are nothing to me but just another butthead. I will beat you the heck up with precision the likes of which has never been seen before on this Earth, mark my dang words. You think you can get away with saying that baloney to me on the glowy type-box? Think again, doodiehead. As we speak I am contacting my secret network of teachers across the USA and your parents are being called to pick you up right now so you better prepare for the spanking, junior. The spanking that wipes out the dumb little thing you call your playtime. You're in big darn trouble, kid. I can be anywhere, anytime, and I can wedgie you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed fartfights, but I have access to the entire arsenal of the United States PTA and I will use it to its full extent to wipe your dorky bottom off the face of the playground, you little poopypants. If only you could have known what serious punishments your little "smartypants" comment was about to bring down upon you, maybe you would have held your goshdarned tongue. But you couldn't, you didn't, and now you're paying the price, you silly doofus. I will spray boogers all over you and you will cry about it. You're frickin grounded, buttmunch.

**Comment by Drag0n0x** [comment]
wot the fok did ye just say 2 me m8? i dropped out of newcastle primary skool im the sickest bloke ull ever meet & ive nicked 300 candy bars from tha corner store. im trained in street fitin’ & im the strongest foker in tha entire newcastle gym. yer nothin to me but a cheeky lil dickhead w/ a hot mum & fake bling. ill waste u and smash a fokin bottle oer yer head bruv, i swer 2 christ. ya think u can fokin run ya gabber at me whilst sittin on yer arse behind a lil screen? think again wanka. im callin me homeboys rite now preparin for a proper rumble. tha rumble thatll make ur nan sore jus hearin about it. yer a waste bruv. my homeboys be all over tha place & ill beat ya to a proper fokin pulp with me fists wanka. if i aint satisfied w/ that ill borrow me m8s cricket paddle & see if that gets u the fok out o’ newcastle ya daft kunt. if ye had seen this bloody fokin mess commin ye might a’ kept ya gabber from runnin. but it seems yer a stewpid lil twat, innit? ima shite fury & ull drown in it m8. ur in proper mess ya knobhead.

**Comment by roflwaffl** [comment]
"hi every1 im new!!!!!!! holds up spork my name is katy but u can call me t3h PeNgU1N oF d00m!!!!!!!! lol…as u can see im very random!!!! thats why i came here, 2 meet random ppl like me _… im 13 years old (im mature 4 my age tho!!) i like 2 watch invader zim w/ my girlfreind (im bi if u dont like it deal w/it) its our favorite tv show!!! bcuz its SOOOO random!!!! shes random 2 of course but i want 2 meet more random ppl =) like they say the more the merrier!!!! lol…neways i hope 2 make alot of freinds here so give me lots of commentses!!!! DOOOOOMMMM!!!!!!!!!!!!!!!! <--- me bein random again _^ hehe…toodles!!!!!
love and waffles,
t3h PeNgU1N oF d00m"

**Comment by Michaelfonzolo** [comment]
░░░░░░▄▄▄░░▄██▄
░░░░░▐▀█▀▌░░░░▀█▄
░░░░░▐█▄█▌░░░░░░▀█▄
░░░░░░▀▄▀░░░▄▄▄▄▄▀▀
░░░░▄▄▄██▀▀▀▀
░░░█▀▄▄▄█░▀▀
░░░▌░▄▄▄▐▌▀▀▀
▄░▐░░░▄▄░█░▀▀ U HAVE BEEN SPOOKED BY THE
▀█▌░░░▄░▀█▀░▀
░░░░░░░▄▄▐▌▄▄
░░░░░░░▀███▀█░▄
░░░░░░▐▌▀▄▀▄▀▐▄SPOOKY SKELETON
░░░░░░▐▀░░░░░░▐▌
░░░░░░█░░░░░░░░█
░░░░░▐▌░░░░░░░░░█
░░░░░█░░░░░░░░░░▐▌SEND THIS TO 6 PPL OR SKELETONS WILL EAT YOU

**Pull request closed without merging**
